// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2PDiLMZeqxirD5CZAMdV7HxL8uT15IPQ',
    appId: '1:154832305954:web:a53aee0d077974e0daef7b',
    messagingSenderId: '154832305954',
    projectId: 'sensor-data-4923f',
    authDomain: 'sensor-data-4923f.firebaseapp.com',
    databaseURL: 'https://sensor-data-4923f-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-data-4923f.firebasestorage.app',
    measurementId: 'G-9WKKBC4BCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtmkfaK5oDu1KlqnUTm0SkdlqEjeIDdbE',
    appId: '1:154832305954:android:cc3193cbb146744cdaef7b',
    messagingSenderId: '154832305954',
    projectId: 'sensor-data-4923f',
    databaseURL: 'https://sensor-data-4923f-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-data-4923f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu1EjQW_LTKw0BqUGMItgC2wyzQWkJwUo',
    appId: '1:154832305954:ios:386f3f4aa8aba50bdaef7b',
    messagingSenderId: '154832305954',
    projectId: 'sensor-data-4923f',
    databaseURL: 'https://sensor-data-4923f-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-data-4923f.firebasestorage.app',
    iosBundleId: 'com.example.aidoSensorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu1EjQW_LTKw0BqUGMItgC2wyzQWkJwUo',
    appId: '1:154832305954:ios:386f3f4aa8aba50bdaef7b',
    messagingSenderId: '154832305954',
    projectId: 'sensor-data-4923f',
    databaseURL: 'https://sensor-data-4923f-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-data-4923f.firebasestorage.app',
    iosBundleId: 'com.example.aidoSensorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2PDiLMZeqxirD5CZAMdV7HxL8uT15IPQ',
    appId: '1:154832305954:web:d1145c800ade58a9daef7b',
    messagingSenderId: '154832305954',
    projectId: 'sensor-data-4923f',
    authDomain: 'sensor-data-4923f.firebaseapp.com',
    databaseURL: 'https://sensor-data-4923f-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-data-4923f.firebasestorage.app',
    measurementId: 'G-0Z3FBNCRW5',
  );

}