// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdcrpyd2JRwY7SM9TKWJ5hYGMn2py-1g8',
    appId: '1:913005511206:web:dc1eccc4aaf9c16e29dce7',
    messagingSenderId: '913005511206',
    projectId: 'aido-c0e64',
    authDomain: 'aido-c0e64.firebaseapp.com',
    databaseURL: 'https://aido-c0e64-default-rtdb.firebaseio.com',
    storageBucket: 'aido-c0e64.firebasestorage.app',
    measurementId: 'G-MQ43812M3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDvn_Ye6nxzljqlOf82AG1vwXMc-TQ11E',
    appId: '1:913005511206:android:7301b88c2325757729dce7',
    messagingSenderId: '913005511206',
    projectId: 'aido-c0e64',
    databaseURL: 'https://aido-c0e64-default-rtdb.firebaseio.com',
    storageBucket: 'aido-c0e64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0jBIaPbAtHKuu3CaUsHrC70RBOtXdK7A',
    appId: '1:913005511206:ios:f9f50a7281d2b09129dce7',
    messagingSenderId: '913005511206',
    projectId: 'aido-c0e64',
    databaseURL: 'https://aido-c0e64-default-rtdb.firebaseio.com',
    storageBucket: 'aido-c0e64.firebasestorage.app',
    iosBundleId: 'com.example.aidoSensorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0jBIaPbAtHKuu3CaUsHrC70RBOtXdK7A',
    appId: '1:913005511206:ios:f9f50a7281d2b09129dce7',
    messagingSenderId: '913005511206',
    projectId: 'aido-c0e64',
    databaseURL: 'https://aido-c0e64-default-rtdb.firebaseio.com',
    storageBucket: 'aido-c0e64.firebasestorage.app',
    iosBundleId: 'com.example.aidoSensorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdcrpyd2JRwY7SM9TKWJ5hYGMn2py-1g8',
    appId: '1:913005511206:web:a572a462f05e4fba29dce7',
    messagingSenderId: '913005511206',
    projectId: 'aido-c0e64',
    authDomain: 'aido-c0e64.firebaseapp.com',
    databaseURL: 'https://aido-c0e64-default-rtdb.firebaseio.com',
    storageBucket: 'aido-c0e64.firebasestorage.app',
    measurementId: 'G-S3BYSEK5B9',
  );

}